spring.application.name=aranegar
server.port=1533

#Elasticsearch
spring.elasticsearch.username=elastic
spring.elasticsearch.password=pania1234
spring.elasticsearch.uris=http://192.168.10.153:9200

#Postgres
spring.r2dbc.url=r2dbc:postgresql://192.168.10.80:5432/diaco-auth-db
spring.r2dbc.username=postgres
spring.r2dbc.password=pania123

#RabbitMQ
spring.rabbitmq.host=192.168.10.160
spring.rabbitmq.username=pania
spring.rabbitmq.password=1qaz2wsx
spring.rabbitmq.port=5672
rabbit.queue.request=aranegar-request
rabbit.queue.result=aranegar-result

#minIO
minio.url=http://192.168.10.77:9000
minio.access-key=pania
minio.secret-key=paniaqaz123qwe
minio.bucket.name=diaco-aranegar

jwtSecret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437